### ISSUE TITLE
[기획서] 로그인 화면에 관해 + 글씨를 못알아봄

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/able-mall-front#2]
1. 사용가능 금액이라면 포인트 충전식인가요?
2. 첫번째 page 에 장애정리분류? 그것은 무슨 말인가요?
3. 이름 등이 보이게 라는 말은 닉네임(혹은 실명), 이메일 정도 보이라는 말과 같나요?

**Comment by c2lv** [comment]
현재 문의 드렸고 답변 오는 대로 코멘트 남기겠습니다!

**Comment by c2lv** [comment]
1. 포인트 충전식 괜찮습니다!
2. 사용자가 어떤 장애인에 해당하는지(발달장애인, 자폐장애인 등...)이 나오면 됩니다!
3. 이름은 실명이 보이게 해주세요! 기타 해당 유저에 대한 정보 띄워주는 것 괜찮습니다!
